//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSF_MAPS_DATA_ACCESS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSFEntities : DbContext
    {
        public GSFEntities()
            : base("name=GSFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Batiment> Batiment { get; set; }
        public DbSet<Etage> Etage { get; set; }
        public DbSet<Locaux> Locaux { get; set; }
        public DbSet<Site> Site { get; set; }
        public DbSet<Zone> Zone { get; set; }
    }
}
